name: Label

on:
  pull_request_review:
    types:
      - submitted

jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      if: github.event_name == 'pull_request_review'
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "automerge"
        REMOVE_LABEL: "awaiting%20review"